-- SQL to create the notifications table for LegalAI
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT,
    type TEXT DEFAULT 'case_assigned', -- 'case_assigned', 'hearing_reminder', 'status_update'
    reference_id TEXT, -- case_id or similar
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for faster retrieval by email
CREATE INDEX IF NOT EXISTS idx_notifications_user_email ON public.notifications(user_email);
-- Index for unread filtering
CREATE INDEX IF NOT EXISTS idx_notifications_read ON public.notifications(read) WHERE read = false;

-- Enable Row Level Security (RLS)
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Allow users to see their own notifications
CREATE POLICY "Users can view their own notifications"
ON public.notifications FOR SELECT
TO authenticated
USING (auth.jwt() ->> 'email' = user_email);

-- Allow users to update their own notifications (mark as read)
CREATE POLICY "Users can update their own notifications"
ON public.notifications FOR UPDATE
TO authenticated
USING (auth.jwt() ->> 'email' = user_email);

-- Allow system/admin to insert notifications 
-- (Assuming service role handles this, but adding a policy for robustness)
CREATE POLICY "Admins can insert notifications"
ON public.notifications FOR INSERT
TO authenticated
WITH CHECK (true); -- Usually restricted by backend logic
